//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOD_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Driver
    {
        public int DriverID { get; set; }
        public string Name { get; set; }
        public int RacesEntered { get; set; }
        public int Podiums { get; set; }
        public bool Champion { get; set; }
        public int TeamID { get; set; }
    
        public virtual Team Team { get; set; }
    }
}
